name: service1

env:
    SERVICE_PATH: services/service1

on:
    push:
        paths:
            - 'services/service1/**'

jobs:

    build:
        runs-on: ubuntu-18.04
        steps:
        - uses: actions/checkout@v2
        - name: build
          run: go build -i -v $SERVICE_PATH/main.go

    lint:
        runs-on: ubuntu-latest
        needs: [build]
        steps:
        - uses: actions/checkout@v2
        - uses: actions/setup-go@v2
          with:
            stable: 'false'
            go-version: '1.14.1'
        - name: lint
          run: |
            curl -sSfL https://raw.githubusercontent.com/golangci/golangci-lint/master/install.sh | sh -s -- -b $(go env GOPATH)/bin v1.26.0
            golangci-lint run $SERVICE_PATH
        
    test:
        strategy:
            matrix:
                go version: [1.12.x, 1.13.x, 1.14.x]
                platform: [ubuntu-latest]
        runs-on: ${{ matrix.platform }}
        needs: [build]
        steps:
        - name: install Go and checkout code
          uses: actions/setup-go@v2
          with:
            go-version: ${{ matrix.go-version }}
        - uses: actions/checkout@v2
        - name: test
          run: |
            go test ./$SERVICE_PATH/... -tags=unit -v -coverprofile cover.out
            go tool cover -func cover.out | grep total
            go tool cover -html=cover.out -o cover.html

    publish:
        runs-on: ubuntu-latest
        needs: [lint, test]
        if: github.ref == 'refs/heads/main'
        steps:
        - name: checkout the repo
          uses: actions/checkout@v2
        - name: build and push to docker hub
          uses: docker/build-push-action@v1
          with:
            path: services/service1
            username: ${{ secrets.DOCKER_USERNAME }}
            password: ${{ secrets.DOCKER_PASSWORD }}
            repository: cristinaespiritu/pocpublic
            tag_with_sha: true