name: service1

on:
    push:
        paths:
            - 'services/service1/**'

jobs:

    # build-service1:
    #     runs-on: ubuntu-18.04
    #     steps:
    #     - uses: actions/checkout@v2
    #     - name: build-service1
    #       run: go build -i -v services/service1/main.go

    # lint:
    #     runs-on: ubuntu-latest
    #     needs: [build-service1]
    #     steps:
    #     - uses: actions/checkout@v2
    #     - uses: actions/setup-go@v2
    #       with:
    #         stable: 'false'
    #         go-version: '1.14.1'
    #     - name: lint-service1
    #       run: |
    #         curl -sSfL https://raw.githubusercontent.com/golangci/golangci-lint/master/install.sh | sh -s -- -b $(go env GOPATH)/bin v1.26.0
    #         golangci-lint run
        
    # test:
    #     strategy:
    #         matrix:
    #             go version: [1.12.x, 1.13.x, 1.14.x]
    #             platform: [ubuntu-latest]
    #     runs-on: ${{ matrix.platform }}
    #     needs: [build-service1]
    #     steps:
    #     - name: install Go and checkout code
    #       uses: actions/setup-go@v2
    #       with:
    #         go-version: ${{ matrix.go-version }}
    #     - uses: actions/checkout@v2
    #     - name: test-service1
    #       run: |
    #         go test ./... -tags=unit -v -coverprofile cover.out
    #         go tool cover -func cover.out | grep total
    #         go tool cover -html=cover.out -o cover.html

    publish:
        runs-on: ubuntu-latest
        # needs: [lint, test]
        # if: github.event_name == 'push' && github.ref == 'refs/heads/master'
        steps:
        - name: checkout the repo
          uses: actions/checkout@v2
        
        #docker build and push - manual
        - name : build and push docker image for service1
          run: |
            docker build -t service1 -f services/service1/Dockerfile .
            docker login -u ${{ secrets.DOCKER_USERNAME }} -p ${{ secrets.DOCKER_PASSWORD }}
            docker tag service1 $REPO:service1-$tag_with_sha
            docker push $REPO

        # #docker build and push - using actions
        # - name: build and push to docker hub
        #   uses: docker/build-push-action@v1
        #   with:
        #     path: ~/Dockerfile
        #     username: ${{ secrets.DOCKER_USERNAME }}
        #     password: ${{ secrets.DOCKER_PASSWORD }}
        #     repository: cristinaespiritu/pocpublic
        #     tag_with_sha: true